name: network_tools_flutter
description: Extended features of network_tools package for flutter framework supporting iOS and Android
version: 2.0.2
issue_tracker: https://github.com/osociety/network_tools_flutter/issues
repository: https://github.com/osociety/network_tools_flutter

environment:
  sdk: ">=3.2.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  
topics:
  - network
  - ping
  - arp
  - port
  - scanner

funding:
  - https://liberapay.com/OpenSociety/donate
  - https://ko-fi.com/fs0c13ty

dependencies:
  flutter:
    sdk: flutter
  
  # Multi-platform network ping utility.
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  fake_http_client: ^1.0.0
  flutter_isolate: ^2.0.4
  # Debugging and error logging.
  logging: ^1.2.0
  # Deal with internationalized/localized messages and more.
  intl: ">=0.18.0 <0.20.0"
  network_tools: ^5.0.0
  path_provider: ^2.1.1
  universal_io: ^2.2.2
  nsd: ">=2.3.1 <4.0.0"
  # Performing mDNS queries (e.g. Bonjour, Avahi).
  multicast_dns: ^0.3.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
